### PR TITLE
remove some non working codes & add new tests

### LINKED ISSUE #122: Correcting and making tests for Java codes
There are many Java algorithms which do not run and some which don't have proper comments to explain the code. Is someone interested in correcting those and making proper unit tests for them?

### PR DESCRIPTION
**Pull request by MahmoudMabrok**
- REMOVE SOME NON WORKING CODES 
- ADD NEW TEST

FIX #122

### CODE REVIEW

**Comment by aniketsharma00411** [comment]
Rest all work or are you still working?

**Comment by MahmoudMabrok** [comment]
I CHECKED Array folder

**Comment by aniketsharma00411** [comment]
Also can you rename files to follow snake_case?
Check all other language directories every file name is now in snake_case. This will make the files more organized.

**Comment by MahmoudMabrok** [comment]
codes are poorly documented

**Comment by aniketsharma00411** [comment]
> codes is poorly documented

Which ones?

**Comment by aniketsharma00411** [comment]
> I CHECKED Array folder

No issue. Take your time.

**Comment by MahmoudMabrok** [comment]
files i worked on it in that folder, 
so i have energy to continue with these codes

**Comment by aniketsharma00411** [comment]
> files i worked on it in that folder,
> so i have energy to continue with these codes

Just delete the undocumented codes if you can't figure out what they do.

**Comment by MahmoudMabrok** [comment]
for now i will not continue with theses codes, may be later.

**Pull request merged**
