### PR TITLE
Added 3 sorting algorithms namely Quick sort, Merge sort & Selection sort

### PR DESCRIPTION
**Pull request by hryxna**
Hello @aniketsharma00411 I came across your repo while I was going through the repo I contributed to recently
after checking the algorithms of your repo I found out that 3 algorithms were missing from the folder Java/Sorting 
So I thought I should fill this gap by contributing to your repo 😄.
Kindly check the programs and if you find it satisfying then feel free to add it 😃.

### CODE REVIEW

**Comment by aniketsharma00411** [comment]
Please read the CONTRIBUTING.md file and follow instructions there.

https://github.com/aniketsharma00411/algorithmsUse/blob/master/CONTRIBUTING.md

**Comment by hryxna** [comment]
> Please read the CONTRIBUTING.md file and follow instructions there.
> 
> https://github.com/aniketsharma00411/algorithmsUse/blob/master/CONTRIBUTING.md

Hello, @aniketsharma00411 I have read the README.md and made the necessary changes.
have a look at it 😄.

**Comment by aniketsharma00411** [comment]
Rename merge_Sort to merge_sort. Similarly, for other two files. Also, in the README files you are writing insertion sort in place of selection sort.

**Comment by hryxna** [comment]
Sorry, my bad 😓 @aniketsharma00411.
I guess no more issues now 😅

**Pull request merged**
