### PR TITLE
Added cocktail sort Algorithm for C++

### PR DESCRIPTION
**Pull request by joey2031**
For issue #1- "Add any Algorithm which is not already present in its respective Programming Language directory". Uploaded Cocktail_Sort.cpp in the C++ folder.

### CODE REVIEW

**Comment by aniketsharma00411** [comment]
Please read the CONTRIBUTING.md file and follow instructions there.

https://github.com/aniketsharma00411/algorithmsUse/blob/master/CONTRIBUTING.md

**Comment by aniketsharma00411** [comment]
Can you rename the file to cocktail_sort.cpp?

**Comment by joey2031** [comment]
> Can you rename the file to cocktail_sort.cpp?

Sure ill do that now

**Comment by joey2031** [comment]
Fixed everything, if there is anything I missed just let me know! Thanks!

**Pull request merged**
