### PR TITLE
Solve Mazeproblem with backtracking

### PR DESCRIPTION
**Pull request by 0utplay**
This PR solves the Maze problem and uses backtracking

### CODE REVIEW

**Comment by aniketsharma00411** [comment]
Please read the CONTRIBUTING.md file and follow instructions there.

https://github.com/aniketsharma00411/algorithmsUse/blob/master/CONTRIBUTING.md

**Comment by aniketsharma00411** [comment]
Why have you added the .gitignore file?

**Comment by 0utplay** [comment]
So nobody will commit stuff thats generated from the idea and not necessary to be in the repo

**Comment by aniketsharma00411** [comment]
> So nobody will commit stuff thats generated from the idea and not necessary to be in the repo

Remove that for now. I will look into it later.

**Pull request merged**
