### PR TITLE
Quicksort algorithm created and added

### PR DESCRIPTION
**Pull request by Pandiurex**

### CODE REVIEW

**Comment by aniketsharma00411** [comment]
Can you give a single .cpp file?

**Comment by Pandiurex** [comment]
sure give me a moment

**Comment by aniketsharma00411** [comment]
Also, as you know proper English, please write the comments in English only.

**Comment by Pandiurex** [comment]
its done my friend

**Comment by aniketsharma00411** [comment]
Thanks

**Pull request merged**
