### PR TITLE
updating branch

### PR DESCRIPTION
**Pull request by utkarshrai2811**
Implemented Merge, Selection and Bubble sort in Rust language and uodated the README accordingly.

### CODE REVIEW

**Comment by aniketsharma00411** [comment]
Can you write the names in snake case. Eg. Rename the file BubbleSort.rs to bubble_sort.rs

**Comment by utkarshrai2811** [comment]
> Can you write the names in snake case. Eg. Rename the file BubbleSort.rs to bubble_sort.rs

Yeah I'll rename the files

**Comment by aniketsharma00411** [comment]
> Yeah I'll rename the files

Now there are two files for each, one with the old name and one with new name.

**Comment by utkarshrai2811** [comment]
> > Yeah I'll rename the files
> 
> Now there are two files for each, one with the old name and one with new name.
Removed the duplicate ones

**Comment by utkarshrai2811** [comment]
> > Yeah I'll rename the files
> 
> Now there are two files for each, one with the old name and one with new name.

Removed the duplicate files

**Comment by aniketsharma00411** [comment]
Thanks

**Pull request merged**
