### PR TITLE
Created bubblesort.swift

### PR DESCRIPTION
**Pull request by ayushontop**
Bubble Sort Algorithm in swift

### CODE REVIEW

**Comment by aniketsharma00411** [comment]
You didn't update the README files. It was written in CONTRIBUTING.md file.

https://github.com/aniketsharma00411/algorithmsUse/blob/master/CONTRIBUTING.md

**Comment by ayushontop** [comment]
Sorry for inconvenience, Updated succesfully

**Comment by aniketsharma00411** [comment]
Rename the file to 'bubble_sort.swift'.

This was mentioned in CONTRIBUTING.md

**Comment by ayushontop** [comment]
Anything else ?

**Pull request merged**
