### PR TITLE
Added Stack and Queue in Python

### PR DESCRIPTION
**Pull request by NachiketaVadera**
# Python

## Stack
Using the `list` data type, implemented stack using the `append()` and `pop()` functions.

## Queue
Using the `list` data type, made a queue using the `append()` and `pop(0)` functions.

### CODE REVIEW

**Comment by aniketsharma00411** [comment]
Please make the program generalized.

**Comment by NachiketaVadera** [comment]
Hey @aniketsharma00411. Thank you for your feedback. Generalized in what terms exactly?

**Comment by aniketsharma00411** [comment]
Use classes to create a queue or stack object. Currently, we are working on a list only.

**Comment by NachiketaVadera** [comment]
@aniketsharma00411 Thank you. Could you please check the code now?

**Comment by aniketsharma00411** [comment]
Now its fine.

**Pull request merged**
