### PR TITLE
Added Cycle Sort, Bucket Sort and Shell Sort Algorithm

### PR DESCRIPTION
**Pull request by DakshJn**
Added Cycle Sort Algorithm
Updated READMEs also

### CODE REVIEW

**Comment by aniketsharma00411** [comment]
Can you rename the files from PascalCase to snake_case?

**Comment by DakshJn** [comment]
These are the 2 sorting algoritms . Cycle sort and Bucket Sort.
Whic file to rename, PascalCase??

**Comment by aniketsharma00411** [comment]
Rename all the files.
For eg.: Rename CycleSort.cpp to cycle_sort.cpp and BubbleSort.cpp to bubble_sort.cpp and same for ShellSort.cpp to shell_sort.cpp

This is given in CONTRIBUTING.md

**Comment by DakshJn** [comment]
I have Renamed the files Cycle sort, Bucket sort and Shell sort. Also updated them in READMEs.

**Pull request merged**
