### PR TITLE
add python tree alogrithms

### PR DESCRIPTION
**Pull request by chawlapalak**
- Added balanced binary tree check algorithm
- added level order traversal for a binary tree algorithm

### CODE REVIEW

**Comment by aniketsharma00411** [comment]
Please update the README files also.

**Comment by chawlapalak** [comment]
> 
> 
> Please update the README files also.

Hi Aniket:

Updated. Let me know if you need any further changes. Thanks!

**Comment by aniketsharma00411** [comment]
Tree Algorithms should be 4-level heading in README.md. Also, update the Python/README.md.

Add comments regarding the programs at the start too.

**Comment by chawlapalak** [comment]
> 
> 
> Tree Algorithms should be 4-level heading in README.md. Also, update the Python/README.md.
> 
> Add comments regarding the programs at the start too.

Updated.

**Comment by aniketsharma00411** [comment]
> > Tree Algorithms should be 4-level heading in README.md. Also, update the Python/README.md.
> > Add comments regarding the programs at the start too.
> 
> Updated.

You have not updated README.md in Python directory. It's mentioned in CONTRIBUTING.md

**Comment by chawlapalak** [comment]
> 
> 
> > > Tree Algorithms should be 4-level heading in README.md. Also, update the Python/README.md.
> > > Add comments regarding the programs at the start too.
> > 
> > 
> > Updated.
> 
> You have not updated README.md in Python directory. It's mentioned in CONTRIBUTING.md

Check now.

**Review by aniketsharma00411 — APPROVED** [review]

**Pull request merged**
