### PR TITLE
Added Hangman Game code in Python and modified typo in README.md file

### PR DESCRIPTION
**Pull request by Sheetalsingh23**
Added Hangman Game code in Python and modified typo in README.md file.

### CODE REVIEW

**Comment by aniketsharma00411** [comment]
Can you update both the README file with your algo name?

**Comment by aniketsharma00411** [comment]
Also add the file in the Python/Miscellaneous/ directory.

**Comment by Sheetalsingh23** [comment]
hey @aniketsharma00411 
For adding the file in Python/Miscellaneous/ directory, do I need to fork the repository again? Because there isn't a folder named  Miscellaneous in my cloned version of this repo. Please help me figure it out.

**Comment by aniketsharma00411** [comment]
I will take care of that.

**Pull request merged**
