### PR TITLE
added heap sort

### PR DESCRIPTION
**Pull request by Astha-Bhushan**
I have added python code for heap sort.
#hacktoberfest

### CODE REVIEW

**Comment by aniketsharma00411** [comment]
Please read the CONTRIBUTING.md file and follow instructions there.

https://github.com/aniketsharma00411/algorithmsUse/blob/master/CONTRIBUTING.md

**Comment by Astha-Bhushan** [comment]
sorry, I am a beginner. I do not know where I am wrong .please guide.

**Comment by Astha-Bhushan** [comment]
i have to update python readme as well .okay .pardon me.

**Comment by aniketsharma00411** [comment]
> i have to update python readme as well .okay .pardon me.

And the [main repo README](https://github.com/aniketsharma00411/algorithmsUse/blob/master/README.md) too.

**Comment by Astha-Bhushan** [comment]
Done

**Comment by Astha-Bhushan** [comment]
please merge it

**Comment by aniketsharma00411** [comment]
In the main README you entered the file under the Rust category.

**Comment by Astha-Bhushan** [comment]
Hey do you removed hactoberfest tag ? Please add it as i am only one pr away.

**Comment by aniketsharma00411** [comment]
> Hey do you removed hactoberfest tag ? Please add it as i am only one pr away.

I never added the tag in your PR. You didn't correct the README I mentioned.

**Comment by aniketsharma00411** [comment]
> In the main README you entered the file under the Rust category.

You were supposed to correct it.

**Pull request closed without merging**
